sonic/epresence_api/urls.py
from django.urls import path
from . import views
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'epresence_api'
urlpatterns = [
    
    path('',views.LoginView, name='loginview'),
    path('login',views.Login),
    path('logout',views.LogoutView, name='logout'),

    path('home/', views.HomeView, name='home'),

    path('Mes_absences/', views.Absences, name='absences_perso'),

    
    
    
    path('Espace_professeur/', views.ProfView, name='professeur'),
    path('Mes_cours/', views.emploi_du_temps_prof, name='emploi_prof'),
    path('notes_prof/', views.Notes_prof, name='notes_prof'),
    path('Absences_élèves/', views.Absences_cours, name='absences_cours'),
    path('Stat_professeur/',views.stat_moyenne_par_matiere_prof, name='stat_prof'),

    
    
    path('Espace_etudiant/', views.StudentView, name='etudiant'),
    path('Emplois_du_temps/', views.emploi_du_temps_eleve, name='emploi_eleve'),
    path('notes_eleve/', views.Notes_eleve, name='notes_eleve'),
    path('Stat_élève/',views.stat_note_par_matiere_eleve, name='stat_eleve'),
    
    path('choisir_groupe/', views.choisir_groupe, name='choisir_groupe'),
    path('choisir_groupe_abs/', views.choisir_groupe_abs, name='choisir_groupe_abs'),

    path('choisir_matiere/', views.choisir_matiere, name='choisir_matiere'),

    path('saisir_note/', views.eleves_liste_notes, name='saisir_note'),
    path('soumettre_notes/', views.soumettre_notes, name='soumettre_notes'),
    
    path('saisir_abs/', views.eleves_liste_abs, name='saisir_abs'),
    path('soumettre_abs/', views.soumettre_abs, name='soumettre_abs'),

    path('reset_password/',views.ChangePassword, name='reset_password'),
        
    path('verify/', views.empty_verify_view, name='empty-verify-view'),

    
    
    
    path('del/', views.delsession),

    path('download_csv/', download_csv, name='download_csv'),

]

sonic/epresence_api/templates/epresence_api/Password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/ChangePassword.css' %}"/>
    <title>Change Password</title>
</head>
<body>
  <div class="change-password-container">
    <h2>Changer le mot de passe</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
      <button type="submit" class="change-button">Changer le mot de passe</button>
    </form>
    <p class="message"></p>
  </div>
</body>
</html>

sonic/epresence_api/templates/epresence_api/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block styles %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/Login.css' %}"/>
    {% endblock %}
    <title>Change Password Page</title>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
        <script>
            alert("{{ message }}");
        </script>
        {% endfor %}
    {% endif %}
    <section class="login-container">
        <img src="{% static 'epresence_api/images/E-Presence.png' %}" alt="e-Presence Logo" class="logo">
        <h2>Mon Espace e-presence</h2>
        <h3>Changer le mot de passe</h3>
        <form action='' method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" id="mon-pseudo" required/>
            </div>
            <div class="form-group">
                <label for="password">Mot de passe</label>
                <input type="password" name="password" id="mon-mdp" required/>
            </div>
            <div class="form-group">
                <input type="submit" name="envoi" value="Valider" class="login-button"/>
            </div>
        </form>
        <a href="{% url 'epresence_api:loginview' %}" class="lien vers password ">Se connecter</a>
    </section>
</body>
</html>

sonic/epresence_api/templates/epresence_api/choisir_groupe.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/common.css' %}"/>
    <title>Choisir un Groupe</title>
    <style>
        /* Style pour améliorer l'apparence du formulaire */
        .container {
            max-width: 500px;
            margin: 50px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-label {
            display: block;
            margin-bottom: 5px;
        }
        .form-control {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .btn-primary {
            background-color: #007bff;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
  <div class="container">
    <h2>Choisir un Groupe</h2>
    <p>Utilisateur : {{ first_name }} {{ last_name }}</p>
    <form method="post" action="{% url 'epresence_api:choisir_groupe' %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="group" class="form-label">Sélectionnez un groupe :</label>
        <select name="group" id="group" class="form-control">
          {% for row in groupes %}
            <option value="{{ row.NomGroupe }}">{{ row.NomGroupe }}</option>
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Suivant</button>
    </form>
  </div>
</body>
</html>

sonic/epresence_api/templates/epresence_api/choisir_groupe_abs.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/common.css' %}"/>
    <title>Choisir un Groupe</title>
    <style>
        /* Style pour améliorer l'apparence du formulaire */
        .container {
            max-width: 500px;
            margin: 50px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-label {
            display: block;
            margin-bottom: 5px;
        }
        .form-control {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .btn-primary {
            background-color: #007bff;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
  <div class="container">
    <h2>Choisir un Groupe</h2>
    <p>Utilisateur : {{ first_name }} {{ last_name }}</p>
    <form method="post" action="{% url 'epresence_api:choisir_groupe_abs' %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="group" class="form-label">Sélectionnez un groupe :</label>
        <select name="group" id="group" class="form-control">
          {% for row in groupes %}
            <option value="{{ row.NomGroupe }}">{{ row.NomGroupe }}</option>
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Suivant</button>
    </form>
  </div>
</body>
</html>

sonic/epresence_api/templates/epresence_api/choisir_seance.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/common.css' %}"/>
    <title>Choisir une Séance</title>
    <style>
        .container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-label {
            display: block;
            margin-bottom: 5px;
        }
        .form-control {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .btn-primary {
            background-color: #007bff;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
  <div class="container">
    <h2>Choisir une Séance</h2>
    <p>Utilisateur : {{ first_name }} {{ last_name }}</p>
    <form method="post" action="{% url 'epresence_api:choisir_seance' %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="seance" class="form-label">Sélectionnez une séance :</label>
        <select name="seance" id="seance" class="form-control">
          {% for seance in seances %}
            <option value="{{ seance.id }}">{{ seance.Matiere }} - {{ seance.Date }} - {{ seance.Heure_debut }} à {{ seance.Heure_fin }} - {{ seance.Salle }} - {{ seance.Type_cours }}</option>
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Suivant</button>
    </form>
  </div>
</

sonic/epresence_api/templates/epresence_api/choixClasse.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/common.css' %}"/>
    <title>Choix Classe</title>
</head>
<body>
  <div class="container">
    <h2>Choisir la Classe</h2>
    <form action="{% url 'epresence_api:select_class' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="classe" class="form-label">Classe</label>
        <select id="classe" name="classe" class="form-control">
          <!-- Add your class options here -->
          <option value="classe1">Classe 1</option>
          <option value="classe2">Classe 2</option>
          <!-- More classes can be added here -->
        </select>
      </div>
      <button type="submit" class="button">Valider</button>
    </form>
  </div>
</body>
</html>

sonic/epresence_api/templates/epresence_api/dow.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Télécharger CSV</title>
</head>
<body>
     <a href="{% url 'epresence_api:download_csv' %}">Télécharger le fichier CSV</a>
</body>
</html>

sonic/epresence_api/templates/epresence_api/graphe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Graphique {{nom_graphique}}</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <!-- Inclure Bootstrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Inclure Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body {
            background-color: #333; /* dark gray background */
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* full viewport height */
            margin: 0;
            color: #fff; /* white text color */
        }
        .container {
            height: 80%;
            width: 80%;
            margin: 0 auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Graphique</h1>
        <canvas id="myChart" width="400" height="400"></canvas>
    </div>

    <script>
        // Récupérer les données depuis Django
        var dataFromDjango = {{ data_from_django | safe }};
        
        // Configurer les données pour Chart.js
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: dataFromDjango.labels,
                datasets: [{
                    label: 'note',
                    data: dataFromDjango.data,
                    backgroundColor: 'rgba(255, 99, 132, 1)',
                    borderColor: 'rgba(255, 255, 255, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>
</body>

</html>

sonic/epresence_api/templates/epresence_api/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block styles %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/Login.css' %}"/>
    {% endblock %}
    <title>E-Presence</title>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
        <script>
            alert("{{ message }}");
        </script>
        {% endfor %}
    {% endif %}
    <section class="login-container">
        <img src="{% static 'epresence_api/images/E-Presence.png' %}" alt="e-Presence Logo" class="logo">
        <h2>Mon Espace e-presence</h2>
        <form action='login' method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" id="mon-pseudo" required/>
            </div>
            <div class="form-group">
                <label for="password">Mot de passe</label>
                <input type="password" name="password" id="mon-mdp" required/>
            </div>
            <div class="form-group">
                <input type="submit" name="envoi" value="Valider" class="login-button"/>
            </div>
        </form>
        <a href="{% url 'epresence_api:reset_password' %}" class="lien vers password ">Mot de passe oublié ?</a>
    </section>
</body>
</html>

sonic/epresence_api/templates/epresence_api/prof.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <!-- Link to the external stylesheet using Django's static template tag -->
    {% block styles %}
    <link rel="stylesheet" href="{% static 'epresence_api/styles/accueil.css' %}">
    {% endblock %}
    
    <title>Espace Professeur</title>
</head>
<body>
    <div class="container mt-5 d-flex flex-column align-items-center">
        <!-- Page title -->
        <h1 class="mb-4 page-title">Mon Espace Professeur</h1>
        <div class="button-row">
            <!-- Links to different pages using Django's URL template tag -->
            <a href="{% url 'epresence_api:absences_perso' %}" class="btn btn-primary">Mes absences</a>
            <a href="{% url 'epresence_api:emploi_prof' %}" class="btn btn-primary">Mon emplois du temps</a>
            <a href="{% url 'epresence_api:notes_prof' %}" class="btn btn-primary">Notes étudiants</a>  
            <a href="{% url 'epresence_api:absences_cours' %}" class="btn btn-primary">Absences étudiants</a>
            <a href="{% url 'epresence_api:stat_prof' %}" class="btn btn-primary">Statistiques notes</a> 
            <a href="{% url 'epresence_api:choisir_groupe' %}" class="btn btn-primary">Saisir les notes</a>
            <a href="{% url 'epresence_api:choisir_groupe_abs' %}" class="btn btn-primary">Saisir les absences</a>  
n
        </div>
  </div>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- User logo -->
    <div class="user-logo">
        <img src="{% static 'epresence_api/images/E-Presence.png' %}" alt="User Logo">
    </div>
    <!-- App name -->
    <div class="app-name">
        <h2>Mon Espace Professeur</h2>
    </div>
    <!-- Student name -->
    <div class="student-name">
        <h3>Num. : {{ username }}</h3>
        <h3> {{ first_name }}</h3>
        <h3> {{ last_name }}</h3>
        
    </div>
    <!-- Logout link -->
    <div class="logout">
         <a href="{% url 'epresence_api:logout' %}" class="btn btn-danger">Déconnexion</a>
    </div>
</div>
</body>
</html>

sonic/epresence_api/templates/epresence_api/resetpassword_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/ResetPassword.css' %}"/>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <title>Password Reset Complete</title>
</head>
<body>
  <div class="reset-password-container">
    <h2>Votre mot de passe a été réinitialisé avec succès</h2>
    <a href="{% url 'epresence_api:loginview' %}" class="back-button">Retour à la connexion</a>
  </div>
</body>
</html>

sonic/epresence_api/templates/epresence_api/resetpassword_sent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/ResetPassword.css' %}"/>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <title>Reset Password Sent</title>
</head>
<body>
  <div class="reset-password-container">
    <h2>Un lien de réinitialisation a été envoyé à votre adresse e-mail</h2>
    <a href="{% url 'epresence_api:loginview' %}" class="back-button">Retour à la connexion</a>
  </div>
</body>
</html>

sonic/epresence_api/templates/epresence_api/saisir_abs.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/common.css' %}"/>
    <title>Saisie des Absences</title>
    <style>
        .container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-label {
            display: block;
            margin-bottom: 5px;
        }
        .form-control {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .btn-primary {
            background-color: #007bff;
            color: white;
            padding: 10px 15px;
            border: none.
            border-radius: 5px;
            cursor: pointer;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
        table {
            width: 100%;
            border-collapse: collapse.
            margin-top: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 8px.
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .pagination {
            display: flex.
            justify-content: center.
            padding: 10px 0;
        }
        .pagination a, .pagination span {
            margin: 0 5px.
            padding: 8px 12px.
            border: 1px solid #ddd.
            text-decoration: none.
            color: #007bff;
        }
        .pagination a:hover {
            background-color: #f1f1f1;
        }
        .pagination .current {
            background-color: #007bff.
            color: white.
            border: 1px solid #007bff;
        }
    </style>
</head>
<body>
  <div class="container">
    <h2>Saisie des Absences</h2>
    <p>Utilisateur : {{ first_name }} {{ last_name }}</p>
    <form method="post" action="{% url 'epresence_api:soumettre_abs' %}">
      {% csrf_token %}
      <table>
        <thead>
          <tr>
            <th>Code Etudiant</th>
            <th>Absent</th>
          </tr>
        </thead>
        <tbody>
          {% for eleve in page_obj %}
            <tr>
              <td>{{ eleve.id_students }}</td>
              <td>
                <input type="checkbox" name="absence_{{ eleve.id }}" class="form-control" {% if eleve.absence %}checked{% endif %}>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <button type="submit" class="btn btn-primary">Enregistrer les absences</button>
    </form>
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; première</a>
          <a href="?page={{ page_obj.previous_page_number }}">précédente</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">suivante</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">dernière &raquo;</a>
        {% endif %}
      </span>
    </div>
  </div>
</body>
</html>

sonic/epresence_api/templates/epresence_api/saisir_note.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'epresence_api/styles/common.css' %}"/>
    <title>Saisie des Notes</title>
    <style>
        .container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-label {
            display: block;
            margin-bottom: 5px;
        }
        .form-control {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
        }
        .btn-primary {
            background-color: #007bff;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .pagination {
            display: flex;
            justify-content: center;
            padding: 10px 0;
        }
        .pagination a, .pagination span {
            margin: 0 5px;
            padding: 8px 12px;
            border: 1px solid #ddd;
            text-decoration: none;
            color: #007bff;
        }
        .pagination a:hover {
            background-color: #f1f1f1;
        }
        .pagination .current {
            background-color: #007bff;
            color: white;
            border: 1px solid #007bff;
        }
    </style>
</head>
<body>
  <div class="container">
    <h2>Saisie des Notes</h2>
    <p>Utilisateur : {{ first_name }} {{ last_name }}</p>
    <form method="post" action="{% url 'epresence_api:saisir_note' %}">
      {% csrf_token %}
      <table>
        <thead>
          <tr>
            <th>Code Etudiant</th>
            <th>Note</th>
          </tr>
        </thead>
        <tbody>
          {% for eleve in page_obj %}
            <tr>
              <td>{{ eleve.id_students }}</td>
              <td><input type="number" name="note_{{ eleve.id }}" class="form-control" required></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <button type="submit" class="btn btn-primary">Enregistrer les notes</button>
    </form>
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; première</a>
          <a href="?page={{ page_obj.previous_page_number }}">précédente</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">suivante</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">dernière &raquo;</a>
        {% endif %}
      </span>
    </div>
  </div>
</body>
</html>